sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cd ~
  - wget http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
  - tar xfz qiniu-*.tar.gz
script:
  - npm install -g firebase-tools
  - npm install
  - npm run clean
  - npm run lint
  - npm run build
  - cat scripts/conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > scripts/conf.json
  - ~/qrsync scripts/conf.json
after_script:
  - npm run codecov
cache:
  directories:
    - node_modules
# deploy:
#   provider: s3
#   access_key_id: $S3_ACCESS_KEY_ID
#   secret_access_key: $S3_SECRET_KEY
#   bucket: nobackend.website
#   region: ap-southeast-1
#   skip_cleanup: true
#   local_dir: public
#   on:
#     branch: gh-pages
after_success:
  # - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [ -n "$GITHUB_API_KEY" ]; then
      cd public
      git init
      git -c user.name='Travis CI' -c user.email='travis@jimmylv.com'
      git checkout -b gh-pages
      git add .
      git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
      # Make sure to make the output quiet, or else the API token will leak!
      # This works because the API key can replace your password.
      git push -f -q https://JimmyLv:$GITHUB_API_KEY@github.com/JimmyLv/TAiKu-gh-pages gh-pages &2>/dev/null
    fi