sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - export TZ=Asia/Beijing
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Deployment
  - openssl aes-256-cbc -K $encrypted_68227d46cd32_key -iv $encrypted_68227d46cd32_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # 配置 git 信息
  - git config --global user.name 'Travis CI'
  - git config --global user.email travis@jimmylv.com

script:
#  - npm install -g firebase-tools
#  - rm -rf .happypack
  - npm install
  - npm run clean
  - npm run lint
  - npm run build
#  - cat scripts/conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > scripts/conf.json
#  - wget http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
#  - tar xfz qiniu-*.tar.gz
#  - ./qrsync scripts/conf.json
after_script:
  - npm run test:codecov
cache:
  directories:
    - node_modules
    - ~/.npm
# deploy:
#   provider: s3
#   access_key_id: $S3_ACCESS_KEY_ID
#   secret_access_key: $S3_SECRET_KEY
#   bucket: nobackend.website
#   region: ap-southeast-1
#   skip_cleanup: true
#   local_dir: public
#   on:
#     branch: gh-pages
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
after_success:
  # - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
  - bash <(curl -s https://codecov.io/bash)
  - |
    cd public
    touch .nojekyll
    git init
    git add .
    git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q git@git.coding.net:jimmylv/haiku.git master:coding-pages > /dev/null 2>&1
