sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm install -g firebase-tools
  - npm install
  - npm run clean
  - npm run lint
  - npm run build
  - cat scripts/conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > scripts/conf.json
  - wget http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
  - tar xfz qiniu-*.tar.gz
  - ./qrsync scripts/conf.json
after_script:
  - npm run codecov
cache:
  directories:
    - node_modules
    - ~/.npm
# deploy:
#   provider: s3
#   access_key_id: $S3_ACCESS_KEY_ID
#   secret_access_key: $S3_SECRET_KEY
#   bucket: nobackend.website
#   region: ap-southeast-1
#   skip_cleanup: true
#   local_dir: public
#   on:
#     branch: gh-pages
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
after_success:
  # - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [ -n "$GITHUB_API_KEY" ]; then
      cp CNAME public/CNAME
      cd public
      git init
      git config --global user.email "Travis CI"
      git config --global user.name "travis@jimmylv.com"
      git add .
      git commit -m "Deploy at `date +"%Y-%m-%d %H:%M"`"
      # Make sure to make the output quiet, or else the API token will leak!
      # This works because the API key can replace your password.
      git push -f -q https://$GITHUB_API_KEY@github.com/JimmyLv/TAiKu.git master:gh-pages > /dev/null 2>&1
    fi