export const TOGGLE_SIDEBAR: string = 'TOGGLE_SIDEBAR'
export const TOGGLE_CONTENT: string = 'TOGGLE_CONTENT'

export const FETCH_MUSIC: string = 'FETCH_MUSIC'
export const FETCH_MUSIC_ERROR: string = 'FETCH_MUSIC_ERROR'

export const FETCH_ARTICLE_SUMMARY: string = 'FETCH_ARTICLE_SUMMARY'
export const FETCH_ARTICLE_SUMMARY_ERROR: string = 'FETCH_ARTICLE_SUMMARY_ERROR'

export const FETCH_ARTICLE: string = 'FETCH_ARTICLE'
export const FETCH_ARTICLE_ERROR: string = 'FETCH_ARTICLE_ERROR'
